name: branch-deploy

on:
  issue_comment:
    types: [ created ]

env:
  WORKING_DIR: terraform/

jobs:

  branch-deploy-checks:
    name: branch-deploy-checks
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.branch-deploy.outputs.ref }}
      continue: ${{ steps.branch-deploy.outputs.continue }}
      noop: ${{ steps.branch-deploy.outputs.noop }}

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: GrantBirki/branch-deploy@dceee35f469f925d5f713146e18f2dcca7b9fa88 # pin@v1.1.0

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [ branch-deploy-checks ]
    if: needs.branch-deploy-checks.outputs.continue == 'true'
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2
        with:
          ref: ${{ needs.branch-deploy-checks.outputs.ref }}

      - uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # pin@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        if: needs.branch-deploy-checks.outputs.noop == 'true'
        env:
          TF_VAR_CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        id: terraform
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        if: needs.branch-deploy-checks.outputs.noop != 'true'
        env:
          TF_VAR_CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        id: terraform
        run: terraform apply -no-color -auto-approve
        continue-on-error: true

      - name: Terraform output
        run: |
          TF_OUTPUT="\`\`\`terraform\n${{ steps.terraform.outputs.stdout }}\n\`\`\`"
          echo 'DEPLOY_MESSAGE<<EOF' >> $GITHUB_ENV
          echo "$TF_OUTPUT" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Check Terraform output
        if: steps.terraform.outcome == 'failure'
        run: exit 1
