name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  WORKING_DIR: "terraform/"

jobs:
  new-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: new pull request
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: actions/github-script@f05a81df23035049204b043b50c3322045ce7eb3 # pin@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commentBody = `\
            ### 👋 Thanks for opening a pull request!

            If you are new, please check out the [deployment process](https://github.com/the-hideout/cloudflare#deployment-) to understand how to deploy this pull request. A trimmed down summary will be listed below:

            1. 🧪 Run a noop deployment with \`.deploy noop\` as a comment on this PR
            1. 👀 Observe the CI and \`noop\` output on this pull request to ensure it is passing and doing what it is supposed to do
            1. ✔️ Obtain an approval/review on this pull request
            1. 🚀 Branch deploy your pull request to production - [example](https://github.com/the-hideout/cloudflare/pull/11)

                > Comment \`.deploy\` on this pull request to trigger a deploy. If anything goes wrong, rollback with \`.deploy main\`

            1. 🎉 Merge!
            `

            await github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: commentBody
            })

  deploy:
    if: github.event_name == 'push'
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # pin@v2

      - uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # pin@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        env:
          TF_VAR_CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: terraform apply -auto-approve
